Feature/admin post service test
PuraVida-Technologies/market pull request #22
Opened 2022-07-20 15:16 UTC by murtazamehmudji

2022-07-20 15:57 UTC, miladezzat requested changes
@murtazamehmudji 
One Note: please when you made a PR focus on one thing

2022-07-20 15:57 UTC, miladezzat commented on src/common/constants/post.constants.ts
>  }
why, you change that?

2022-07-20 15:57 UTC, miladezzat commented on src/marketplace/marketplace-post/entities/marketplace-post.entity.ts
> +  @Field(type => POST_STATUS)
`type` not need

2022-07-20 17:19 UTC, murtazamehmudji commented on src/common/constants/post.constants.ts
>  }
Because graphql reads the keys while creating enums. Thus, in enum keys their values need to be same.

2022-07-21 09:08 UTC, miladezzat approved these changes

2022-07-21 09:09 UTC, merged