Feature/marketplace post service test
PuraVida-Technologies/market pull request #26
Opened 2022-07-28 18:27 UTC by murtazamehmudji

2022-07-28 19:54 UTC, miladezzat requested changes

2022-07-28 19:54 UTC, miladezzat commented on src/marketplace/marketplace-post/marketplace-post.service.spec.ts
> +    });
in this, you can create the post by using the `service.create` first, and after that, you must check if it is created or not, by trying to get it

2022-07-29 06:23 UTC, murtazamehmudji commented on src/marketplace/marketplace-post/marketplace-post.service.spec.ts
> +    });
This is done.

2022-07-29 06:38 UTC, miladezzat approved these changes

2022-07-29 06:39 UTC, merged