Add Admin API
PuraVida-Technologies/market pull request #5
Opened 2022-07-05 18:42 UTC by murtazamehmudji

Added Add Category API for Admin

2022-07-05 18:44 UTC, bityogi approved these changes

2022-07-05 19:07 UTC, miladezzat requested changes
Where is the test cases

2022-07-06 08:43 UTC, miladezzat requested changes

2022-07-06 19:35 UTC, miladezzat commented on src/admin/admin-category/admin-category.service.ts
> +    });
```suggestion
    const category = await this.categoryModel.findOne({
      name: createAdminCategoryInput.name, isDeleted: false
    });
```

2022-07-06 19:36 UTC, miladezzat commented on src/admin/admin-category/admin-category.service.ts
> +    return await this.categoryModel.create(createAdminCategoryInput);
```suggestion
    return  this.categoryModel.create(createAdminCategoryInput);
```

2022-07-06 19:36 UTC, miladezzat commented on src/admin/admin-category/admin-category.service.ts
> +    return await this.categoryModel.find();
```suggestion
    return  this.categoryModel.find({ isDeleted: false });
```

2022-07-06 19:36 UTC, miladezzat commented on src/admin/admin-category/admin-category.service.ts
> +    return await this.categoryModel.findOne({ _id: id });
```suggestion
    return this.categoryModel.findOne({ _id: id, isDeleted: false });
```

2022-07-07 18:16 UTC, merged