Feature/update admin category
PuraVida-Technologies/market pull request #8
Opened 2022-07-08 16:28 UTC by murtazamehmudji

2022-07-08 22:56 UTC, miladezzat requested changes

2022-07-08 22:56 UTC, miladezzat commented on src/admin/admin-category/admin-category.service.ts
> +    }
```suggestion
      return this.categoryModel.findOneAndUpdate(
        { _id: id },
        { $set: updateAdminCategoryInput },
        { new: true, lean: true },
      );

```

2022-07-08 22:56 UTC, miladezzat commented on src/admin/admin-category/admin-category.service.ts
> +    const category = await this.categoryModel.findById(id);
```suggestion
    const category = await this.categoryModel.findeOne({ _id: id, isDe;eted: false }).lean();
```

2022-07-08 22:56 UTC, miladezzat commented on src/admin/admin-category/dto/update-admin-category.input.ts
>  import { InputType, Field, Int, PartialType } from '@nestjs/graphql';
please remove `Int` this didn't used

2022-07-08 22:56 UTC, miladezzat commented on src/admin/admin-category/dto/update-admin-category.input.ts
> +  name: string;
```suggestion
  @Field(() => String, { description: 'This is the name of category' , nullable: true})
  @IsOptional()
  @IsNotEmpty()
  @IsString()
  @Length(1)
  name?: string;
```

2022-07-08 22:56 UTC, miladezzat commented on test/admin-category.e2e-spec.ts
> +      const category = await categoryModel.findOne({}).lean();
you must not depend on the other category, you must insert new category here and update it

2022-07-08 22:56 UTC, miladezzat commented on test/admin-category.e2e-spec.ts
> +      const category = await categoryModel.findOne({}).lean();
the same here

2022-07-09 14:14 UTC, murtazamehmudji commented on test/admin-category.e2e-spec.ts
> +      const category = await categoryModel.findOne({}).lean();
@miladezzat It is the same thing. You do all tests on a single category or create a new one.
If category is not added then update doesn't work. If I am inserting new category in update test as well. It would fail anyhow.

2022-07-09 14:22 UTC, murtazamehmudji commented on src/admin/admin-category/dto/update-admin-category.input.ts
> +  name: string;
Update Category › Should fail to update category, bad request

2022-07-09 14:23 UTC, murtazamehmudji commented on test/admin-category.e2e-spec.ts
> +      const category = await categoryModel.findOne({}).lean();
Okay

2022-07-09 14:31 UTC, miladezzat approved these changes

2022-07-09 14:32 UTC, merged