Added delete admin category API and test cases
PuraVida-Technologies/market pull request #9
Opened 2022-07-08 17:03 UTC by murtazamehmudji

2022-07-08 23:01 UTC, miladezzat requested changes

2022-07-08 23:01 UTC, miladezzat commented on test/admin-category.e2e-spec.ts
> +      const category = await categoryModel.findOne({}).lean();
The best practice for testing generally, you must add what you want every test, you must not depend on other data outside your test or another test, and every test must be independent

2022-07-09 14:15 UTC, murtazamehmudji commented on test/admin-category.e2e-spec.ts
> +      const category = await categoryModel.findOne({}).lean();
Okay.

2022-07-10 09:26 UTC, miladezzat approved these changes

2022-07-10 09:29 UTC, merged